-   id: pymend
    name: Pymend
    description: Create, update or convert docstrings in existing Python files, managing several styles.
    entry: pymend
    language: python
    language_version: python3
    types: [text]
    types_or: [python]
    require_serial: true
    args: ["--write","--output=numpydoc"]
